---
title       : Shiny Application and Reproducible Pitch
subtitle    : 
author      : Pramesh Manandhar
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Course Project

This is the final presentation for the Course Project of the "Developing data products" course
- This course is part of the "Data Science specialization"
- The project consists in two activities:
- Create a Shiny application
- Create a presentation in Slidify or Rstudio Presenter to pitch for the application.

---
## Lego Set Database Explorer  

- This Shiny App is for searching and visulizating LEGO Sets information from year 1950 to 2016.
- The total number of set records is 10691 and that of theme records is 104.
- The dataset is from http://rebrickable.com/ that contains the basic information of each set (set id, year, number of pieces, theme, set name).

---
## Web Application functionality

- This application allows you to search for information of Lego sets.
- This application provides with the database on Lego set you want to find out based on the set id, year, number of pieces, theme, set name.
- This appliaction helps you to get information for marketing purpose also.

---
## Pramesh's Shiny Application

- The application can be found in https://datapramesh123.shinyapps.io/Project/

---
